### ISSUE TITLE
Runtime Error when calling the server

### ISSUE THREAD

**Issue by nhafez** [CRLab/pc_object_completion_cnn#2]
The repository was set up as explained [here](https://github.com/CRLab/pc_object_completion_cnn). The mesh_completion_server is started successfully and can works without issues when a partial mesh is requested. When the completed mesh is requested the following error appears:

>  [ERROR] [1528739565.694986, 120.801000]: Exception in your execute callback: axis 1 is out of bounds for array of dimension 1
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/robocup17/Nawal_Projekt/src/pc_scene_completion_ws/src/pc_object_completion_cnn/scripts/shape_completion_server/mesh_completion_server.py", line 166, in completion_cb
    binvox_rw.write(completed_vox, open(temp_binvox_filepath, 'w'))
  File "build/bdist.linux-x86_64/egg/binvox_rw/binvox_rw.py", line 262, in write
    run_starts = np.concatenate((np.array([0]), np.where(voxels_flat[1:] != voxels_flat[:-1])[0] + 1), axis=1)
AxisError: axis 1 is out of bounds for array of dimension 1

A suggestion as to how to fix this error is greatly appreciated!

**Comment by jvarley** [comment]
The axis argument for np.concatenate works differently for different versions of numpy.  You may have to go into binvox_rw.py and put a conditional statement based off the version of numpy that you are using, or just switch axis=1 to axis=0. See [here](https://github.com/CRLab/binvox-rw-py/blob/master/binvox_rw/binvox_rw.py#L265)

**Comment by nhafez** [comment]
Do I have to do anything other than chane that line? Because I get the same error even after changing it.

**Comment by jvarley** [comment]
Your runtime is using:
build/bdist.linux-x86_64/egg/binvox_rw/binvox_rw.py
Is that the file you edited/ did you reinstall after editing.  I would toss in a print statement before the error and make sure you are running the version of binvox_rw.py that you modified.

**Comment by nhafez** [comment]
I had to set it up again and then it worked. Thank you!
